SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `SEGMENT_ID_TABLE`;
CREATE TABLE `SEGMENT_ID_TABLE` (
  `business` varchar(40) NOT NULL COMMENT '业务类型',
  `begin` bigint(40) NOT NULL COMMENT '起始ID',
  `end` bigint(40) NOT NULL COMMENT '最大ID',
  PRIMARY KEY (`business`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

BEGIN;
INSERT INTO `SEGMENT_ID_TABLE` VALUES ('order', 519349, 524349);
INSERT INTO `SEGMENT_ID_TABLE` VALUES ('payment', 51, 5051);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
